language: python
notifications:
  email: true
python:
  - 2.7
  - 3.5
install:
  - pip install -r requirements.txt
script: ignore
deploy:
  provider: pypi
  skip_existing: true
  user: ttvcloud
  password:
    secure: lZTYmRvX1QpjiAtGEHyrI0NexXdT0lPye5jG4MIPwK8BRLoAoUExMmbk35kkFWTEPqHKRCj7YpVCjHZUi9SfjHEC7UhOH0hAAGWLyX4RXwsQmS9LzSA6Wjp4VBldqt49LzDZhi/QlRTJJedpmQdQjbdWZx33ZQCGD8yPIRQukN8xy1VbGhkJNeM2oLRLa1tMTS0Wnl7T5xGfdVchfi5DjlhxwttP3e24P5JP1HoNSc0fXzi92XKwgbnkm+uYlC/046kfj+jEJYwv+qNsP4UxVuGQ9pqL2Ig5TYDHGAskAEQ6bsC4Aq1PlsZTbAcQ7kGwctdoCkRR+RjW2GHz6/UJm4C9BLtSUBVoZ6ubuUbVsN11if0ePy6zXNvk3AuKzmnnKvtJiiDSHRJ47/ZXMld5koiSgcOR9vT4HDmBErH7m5ivKvUo1HAPBqZygp1iPMmuaODTi8IGhDwK3v+PstahnSI4mIh6LYPP5aNlMRX7DrT9Phq0DBmzjUCJtN7VK/3Y+k2+mR/tJn1T3ekvivKgYsDnBUQ5mnU430lzZz4D4ZJ0Ing0z72QyktSthAfVCPMWj8ltWJFAWxvzovLKdWvP00s1F3IueCx43TGivBMSZ1nRhDJXqzz9UG9tHkvzgkvRfpIANi8aiRq6hKlVBv/TGRNJG2mt4g2CgVna3NOWBw=
  on:
    tags: true
    branch: master